### ISSUE TITLE
Verbose Output

### ISSUE THREAD

**Issue by kfrancis** [geckoboard/sql-dataset#17] opened 2018-02-15 17:21 UTC
Is there a way to show any output from this app? It looks like it's running, but I don't see anything happening, I don't see the dataset I'm expecting - I need more information.

**Comment by jnormington** [comment] 2018-02-16 08:42
Hey @kfrancis 

Thanks for raising an issue - what are you seeing when you run the sql-dataset command with your config ? Also what does you command look like for sql-dataset ?

The sql-dataset should output some basic logging by default, below is an example of what you should see when run sql-dataset. Of course it depends on how much data it needs to fetch how long your first output of success or failure occurs.

![image](https://user-images.githubusercontent.com/4930249/36299370-8c49c8f2-12f4-11e8-9334-9702427bbe45.png)

If its outputting nothing - I wonder of the MSSQL driver is hanging when trying to make a connection. We can always create a debugging version of sql-dataset to see where its hanging.

**Comment by kfrancis** [comment] 2018-02-16 19:03
I tried to run it for debug here, but I'm not setup for it on this win-pc. It's just hanging, I don't see anything at all. I have manually made the API calls and set all that up so I know it's not geckoboard, I know it's not the query itself, feels like it just can't connect to the db.

A debug build or at least more verbose output would be great.

**Comment by jnormington** [comment] 2018-02-20 12:07
Hey @kfrancis,

Find attached a zip file with sql-dataset for each of the support OS versions we build for. This version contains some extra logging through out.

As you can see below all the new print statements are prefixed with DEBUG and might help determine where it is failing. Note that I also print out the db connection string we build just in case you notice something weird there. So please ensure before posting to remove those details.

![image](https://user-images.githubusercontent.com/4930249/36423023-3e8b28b4-1636-11e8-94d0-18757107991a.png)

Find the debug version of the builds here - [builds.zip](https://github.com/geckoboard/sql-dataset/files/1739974/builds.zip)

**Comment by kfrancis** [comment] 2018-02-21 05:45
This is what I see:
```
DEBUG: Loading config config.yml
DEBUG: Config finished loading
DEBUG: Validating config
DEBUG: Config validated

DEBUG: Get connection string builder for driver mssql
DEBUG: Got connection string builder using drivers.mssql{}
DEBUG: Building connections string
DEBUG: Built connection string - odbc:server={localhost};port=1433;user id={dbUser};;database=theDb;ApplicationIntent=ReadOnly
DEBUG: Building new client
DEBUG: Making new db connection (but not connecting) - %s
DEBUG: Preparing to start processing datasets
Refresh timer specified run every 1800 seconds until interrupted
```

**Comment by jnormington** [comment] 2018-02-21 09:45
Ah thanks @kfrancis - so it didn't even reach trying to make a connection to the database because after the Refresh timer specified - I was expecting to see

```go
func (ds Dataset) queryDatasource(dc *DatabaseConfig, db *sql.DB) (records []interface{}, err error) {
	fmt.Printf("DEBUG: Querying the database with sql - %s\n", ds.SQL)
	rows, err := db.Query(ds.SQL)
	fmt.Println("DEBUG: Finished querying the database")
```
Ok I see the problem the YAML file under the `datasets` can't be indented correctly, and we don't validate that there is at least one dataset present.

Sorry for the confusion - we'll look to add some validation to prevent this confusion in the future.

Can you check the YAML is correctly formatted as if it isn't indented correctly it won't parse as expected.

You can use the example config here maybe just try replacing the API key and database credentials first then run it and watch it make a db connection and give some output. 
https://github.com/geckoboard/sql-dataset/blob/master/example.yml

then try to update the datasets section after. Hope that helps I think we are closer to resolving. As I was able to reproduce exactly the same issue

![image](https://user-images.githubusercontent.com/4930249/36473256-e76fc614-16eb-11e8-8ba0-25b5e3c5b623.png)

**Comment by kfrancis** [comment] 2018-02-21 14:14
The issue was a mistake I put in before now. I changed `datasets` to `dataset` due to some other issue that appeared to go away if I did that. Putting it back, I'm getting further: 

```Dataset 'edtactivity' errored: Database query failed: Login error: mssql: Login failed for user 'dbUser'.```

I'm 100% sure the user is setup correctly - I can connect and run the same query from that user in SSMS.

**Comment by kfrancis** [comment] 2018-02-21 15:00
Found that issue, all the passwords I was using contained !@ at the beginning. Removing that seems to have moved me futher on.

Next problem (sorry):
> DEBUG: Querying the database with sql - select tdate, nconnections from dbo.EdtActivity()
DEBUG: Finished querying the database
DEBUG: Scanning row values
DEBUG: Scanned row values []interface {}{(*null.Time)(0xc042002720), (*models.Number)(0xc042326360)}
Dataset 'edtactivity' errored: Scan failed: sql: Scan error on column index 0: null: cannot scan type string into null.Time: 2018-02-14T09:00:00

```
datasets:
 - name: edtactivity
   update_type: replace
   sql: "select tdate, nconnections from dbo.EdtActivity()"
   fields:
    - type: datetime
      name: tdate
    - type: number
      name: nconnections
```

I know the data is formatted correctly since I can send this off in an http POST:
```
{"data":[
{"tdate": "2018-02-13T10:00:00","nconnections":25 },
{"tdate": "2018-02-13T11:00:00","nconnections":55 },
{"tdate": "2018-02-13T12:00:00","nconnections":44 },
{"tdate": "2018-02-13T13:00:00","nconnections":52 }
]}
```

**Comment by kfrancis** [comment] 2018-02-21 15:54
Got it, I was formatting the date but it looks like there's some internal formatting going on. Returning the unconverted date seems to have done the trick.

**Comment by jnormington** [comment] 2018-02-22 09:48
Ah great find @kfrancis - so we are not correctly handling special characters in passwords ? I guess we'll need to look into that I thought that we was doing it correctly. As regards to dates yes as long at it is a date we will handle the formatting for Geckoboard dataset as you found out.

So you are successfully up and running - and all there is for us to investigate special characters in the password support ?

**Comment by jnormington** [comment] 2018-04-19 11:08
Released new version which now does some validation check for at least one dataset
https://github.com/geckoboard/sql-dataset/releases/tag/v0.2.2

**Closed by jnormington** 2018-04-19 11:08 UTC
